### ISSUE TITLE
Bro... Namakk video send cheyyan entha cheyya

### ISSUE THREAD

**Issue by souravkl11** [TOXIC-DEVIL/TOXIC-DEVIL#3]
message.sendMessage(fs.readFileSync('output.mp4'), MessageType.video, {mimetype: Mimetype.mpeg, caption: Config.AFN});
    

ithano?

**Comment by toxic-devil** [comment]
> message.sendMessage(fs.readFileSync('output.mp4'), MessageType.video, {mimetype: Mimetype.mpeg, caption: Config.AFN});
> 
> ithano?

await message.client.sendMessage(message.jid, fs.readFileSync('path/to/file'), MessageType.video, {mimetype: Mimetype.mpeg, caption: 'Caption' });

**Comment by souravkl11** [comment]
Thankyou macha 😘

**Comment by toxic-devil** [comment]
> Thankyou macha 😘

💖

**Comment by souravkl11** [comment]
GIF anenkil  MessageType.gif aano

**Comment by toxic-devil** [comment]
> GIF anenkil MessageType.gif aano

Alla ninte number thaa athil doubt chodikk

**Comment by souravkl11** [comment]
> > GIF anenkil MessageType.gif aano
> 
> Alla ninte number thaa athil doubt chodikk

wa.me/919074309534

**Comment by toxic-devil** [comment]
> > > GIF anenkil MessageType.gif aano
> > 
> > 
> > Alla ninte number thaa athil doubt chodikk
> 
> wa.me/919074309534

ok
